lines = [
    "from fastapi import FastAPI, HTTPException",
    "from fastapi.responses import HTMLResponse",
    "import markdown",
    "from pydantic import BaseModel",
    "from ai.analyst import run_autonomous_investigation",
    "",
    'app = FastAPI(title="Autonomous SOC Assistant", version="2.0.0")',
    "",
    "containment_actions = []",
    "",
    "class ContainmentRequest(BaseModel):",
    "    alert_id: str",
    "    action_type: str",
    "    target: str",
    "    approved_by: str",
    "",
    '@app.get("/")',
    "def home():",
    '    return {"message": "Autonomous SOC Assistant Engine is running"}',
    "",
    '@app.get("/health")',
    "def health():",
    '    return {"status": "healthy"}',
    "",
    '@app.post("/alerts/{alert_id}/investigate")',
    "def investigate(alert_id: str):",
    "    try:",
    "        report = run_autonomous_investigation(alert_id)",
    "        return {",
    '            "alert_id": alert_id,',
    '            "status": "INVESTIGATION_COMPLETE",',
    '            "report": report',
    "        }",
    "    except Exception as e:",
    "        raise HTTPException(status_code=500, detail=str(e))",
    "",
    '@app.get("/alerts/{alert_id}/report", response_class=HTMLResponse)',
    "def get_report_html(alert_id: str):",
    "    try:",
    "        raw_markdown = run_autonomous_investigation(alert_id)",
    "        html_content = markdown.markdown(raw_markdown, extensions=['tables', 'fenced_code'])",
    "        html_doc = (",
    '            "